# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    i686-linux = "1f1zszr3n7iry0w11qidvwq7rjr826r4768i8a4afwkchd5i1wsc";
    x86_64-linux = "1f5di1ya3f25psq5nnnn0hh4bznyka7y0p7sb2lp0cs546r15a17";
    armv7l-linux = "1gyi963m7l9rj4dyyldkwrqg7ni6vxkqjcjrkb3bvkxqjdx2k7q3";
    aarch64-linux = "1ai54q0sbdawpvfcl1qahfqhpjf9xvgj0bfkck2iqcq4clymjcyg";
    x86_64-darwin = "07way8947xvr21s2dizby9v8hx0q9i00nqhwc2hqwygh152vgv0p";
    aarch64-darwin = "060ahs19b4d7g54sb7as4p3p1kjfyb17pladk87mlxy0m3s3jz8l";
  };

  urlMap = {
    i686-linux = "https://github.com/snowdreamtech/unistack/releases/download/v0.0.1/unistack_Linux_i386.tar.gz";
    x86_64-linux = "https://github.com/snowdreamtech/unistack/releases/download/v0.0.1/unistack_Linux_x86_64.tar.gz";
    armv7l-linux = "https://github.com/snowdreamtech/unistack/releases/download/v0.0.1/unistack_Linux_armv7.tar.gz";
    aarch64-linux = "https://github.com/snowdreamtech/unistack/releases/download/v0.0.1/unistack_Linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/snowdreamtech/unistack/releases/download/v0.0.1/unistack_Darwin_x86_64.tar.gz";
    aarch64-darwin = "https://github.com/snowdreamtech/unistack/releases/download/v0.0.1/unistack_Darwin_arm64.tar.gz";
  };
  sourceRootMap = {
    i686-linux = "unistack_Linux_i386";
    x86_64-linux = "unistack_Linux_x86_64";
    armv7l-linux = "unistack_Linux_armv7";
    aarch64-linux = "unistack_Linux_arm64";
    x86_64-darwin = "unistack_Darwin_x86_64";
    aarch64-darwin = "unistack_Darwin_arm64";
  };
in
stdenvNoCC.mkDerivation {
  pname = "unistack";
  version = "0.0.1";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = sourceRootMap.${system};

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./unistack $out/bin/unistack
  '';

  meta = {
    description = "Snowdream Tech AI IDE Template is an enterprise-grade, foundational template designed for multi-AI IDE collaboration.";
    homepage = "https://github.com/snowdreamtech/unistack";
    license = lib.licenses.mit;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "armv7l-linux"
      "i686-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
