# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    i686-linux = "0mymdgq2xcg9955x1c0h3nkq2xhifgprd27g9c1s54flc4a4akcm";
    x86_64-linux = "09rvkp5rajihnmc52sm580g3c42vzyypsvnm6q8k8qzl8f3rzrkm";
    armv7l-linux = "1lyfbv0fivmqnzwdiw6m2c1xzgrlnszsqy10zj4kcqkaxqjgvckl";
    aarch64-linux = "1p3409y4rcxd91ga25v02zd2hf3apyvhknbh86nmfcaadwljjjka";
    x86_64-darwin = "1hzcm5gkdb7py5iak00jisgqyhi9mnj0mgyk235nv9q8v1115qzm";
    aarch64-darwin = "0gl0v54qrcrncwh8qsa19zn43f3cfax6vfqf95r5vgs5ahiadq34";
  };

  urlMap = {
    i686-linux = "https://github.com/snowdreamtech/unistack/releases/download/v0.0.2/unistack_Linux_i386.tar.gz";
    x86_64-linux = "https://github.com/snowdreamtech/unistack/releases/download/v0.0.2/unistack_Linux_x86_64.tar.gz";
    armv7l-linux = "https://github.com/snowdreamtech/unistack/releases/download/v0.0.2/unistack_Linux_armv7.tar.gz";
    aarch64-linux = "https://github.com/snowdreamtech/unistack/releases/download/v0.0.2/unistack_Linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/snowdreamtech/unistack/releases/download/v0.0.2/unistack_Darwin_x86_64.tar.gz";
    aarch64-darwin = "https://github.com/snowdreamtech/unistack/releases/download/v0.0.2/unistack_Darwin_arm64.tar.gz";
  };
  sourceRootMap = {
    i686-linux = "unistack_Linux_i386";
    x86_64-linux = "unistack_Linux_x86_64";
    armv7l-linux = "unistack_Linux_armv7";
    aarch64-linux = "unistack_Linux_arm64";
    x86_64-darwin = "unistack_Darwin_x86_64";
    aarch64-darwin = "unistack_Darwin_arm64";
  };
in
stdenvNoCC.mkDerivation {
  pname = "unistack";
  version = "0.0.2";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = sourceRootMap.${system};

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./unistack $out/bin/unistack
  '';

  meta = {
    description = "Snowdream Tech AI IDE Template is an enterprise-grade, foundational template designed for multi-AI IDE collaboration.";
    homepage = "https://github.com/snowdreamtech/unistack";
    license = lib.licenses.mit;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "armv7l-linux"
      "i686-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
