# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    i686-linux = "1lkriy2i0m7waypn9hwqg9x9v84890iqpi1qhhgkiqpnmjiik63n";
    x86_64-linux = "05y5np9s51g598vilm5gv0w1knpq6ri17cpwkyf9mxx15n32cn8x";
    armv7l-linux = "0079gszyyap99sc82vcqr113s9ikmidlwl9xb6jdli7pnsnzs24b";
    aarch64-linux = "02imcsqmmr3g6n2d8p55p99hp7i9nm236fhsqqnpjn628s31rfpa";
    x86_64-darwin = "1jkilyqvi04ya9frzqkzp4w22rjlinvk9s7ar79ji24i2z4j0y4r";
    aarch64-darwin = "19f3b23bbkw1jdn56wr74plbhkrs33g44mpq70dqzlh35ks0r8x6";
  };

  urlMap = {
    i686-linux = "https://github.com/snowdreamtech/unistack/releases/download/v0.0.5/unistack_Linux_i386.tar.gz";
    x86_64-linux = "https://github.com/snowdreamtech/unistack/releases/download/v0.0.5/unistack_Linux_x86_64.tar.gz";
    armv7l-linux = "https://github.com/snowdreamtech/unistack/releases/download/v0.0.5/unistack_Linux_armv7.tar.gz";
    aarch64-linux = "https://github.com/snowdreamtech/unistack/releases/download/v0.0.5/unistack_Linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/snowdreamtech/unistack/releases/download/v0.0.5/unistack_Darwin_x86_64.tar.gz";
    aarch64-darwin = "https://github.com/snowdreamtech/unistack/releases/download/v0.0.5/unistack_Darwin_arm64.tar.gz";
  };
  sourceRootMap = {
    i686-linux = "unistack_Linux_i386";
    x86_64-linux = "unistack_Linux_x86_64";
    armv7l-linux = "unistack_Linux_armv7";
    aarch64-linux = "unistack_Linux_arm64";
    x86_64-darwin = "unistack_Darwin_x86_64";
    aarch64-darwin = "unistack_Darwin_arm64";
  };
in
stdenvNoCC.mkDerivation {
  pname = "unistack";
  version = "0.0.5";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = sourceRootMap.${system};

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./unistack $out/bin/unistack
  '';

  meta = {
    description = "Snowdream Tech AI IDE Template is an enterprise-grade, foundational template designed for multi-AI IDE collaboration.";
    homepage = "https://github.com/snowdreamtech/unistack";
    license = lib.licenses.mit;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "armv7l-linux"
      "i686-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
