# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    i686-linux = "0bgvj4jpq70m22y4729j221akfys72rbj98hm9y9vj3i1qc2vlz8";
    x86_64-linux = "02fk3hiizxid4jcyrxdvbwywdh501w290125lzsll3xp5yw67qhj";
    armv7l-linux = "058kn8rb6m8wn5vs739p38k3pm3rslgg4grfzypzi3ajf59zrmvq";
    aarch64-linux = "0xsa0a64hayzgwqyc0npwxcgfr8knjpgbzx9a93jalbrg5jvcw8x";
    x86_64-darwin = "0gd3qjz34j4bblxr702qii8lixp0xmpsh5wdzc82q520wvsfrc6y";
    aarch64-darwin = "0270yj4gr0zavx20pqab6jj9iyga12rpv58jl7zj00s7w7yqs781";
  };

  urlMap = {
    i686-linux = "https://github.com/snowdreamtech/UniRTM/releases/download/v0.25.0/unirtm_Linux_i386.tar.gz";
    x86_64-linux = "https://github.com/snowdreamtech/UniRTM/releases/download/v0.25.0/unirtm_Linux_x86_64.tar.gz";
    armv7l-linux = "https://github.com/snowdreamtech/UniRTM/releases/download/v0.25.0/unirtm_Linux_armv7.tar.gz";
    aarch64-linux = "https://github.com/snowdreamtech/UniRTM/releases/download/v0.25.0/unirtm_Linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/snowdreamtech/UniRTM/releases/download/v0.25.0/unirtm_Darwin_x86_64.tar.gz";
    aarch64-darwin = "https://github.com/snowdreamtech/UniRTM/releases/download/v0.25.0/unirtm_Darwin_arm64.tar.gz";
  };
  sourceRootMap = {
    i686-linux = "unirtm_Linux_i386";
    x86_64-linux = "unirtm_Linux_x86_64";
    armv7l-linux = "unirtm_Linux_armv7";
    aarch64-linux = "unirtm_Linux_arm64";
    x86_64-darwin = "unirtm_Darwin_x86_64";
    aarch64-darwin = "unirtm_Darwin_arm64";
  };
in
stdenvNoCC.mkDerivation {
  pname = "unirtm";
  version = "0.25.0";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = sourceRootMap.${system};

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./unirtm $out/bin/unirtm
  '';

  meta = {
    description = "UniRTM (Uni Runtime and Tools Manager) is a cross-platform developer toolchain manager.";
    homepage = "https://github.com/snowdreamtech/UniRTM";
    license = lib.licenses.mit;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "armv7l-linux"
      "i686-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
