# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    i686-linux = "1csbbv5rja0jg7zssix89vkpglfv7d8f24qdwyhl439kkbrbjrhb";
    x86_64-linux = "0q9vqahhq8qa44l0g0va2am4cx2hxx68rwnv921kgs1ylc67q9di";
    armv7l-linux = "14kag36ky1xl52c0f13azi45nx6qjpv9alx71g12l8cafp2056zz";
    aarch64-linux = "0sq2cjr49zvgm61xq45ryfhh7mcmlfsr8m43942ck6725mhvv140";
    x86_64-darwin = "0kpidi1rai8kllmca4s8djbzb3vdgxffgswnwa4g7738yfbfk55p";
    aarch64-darwin = "0n716z2aynk81937wkyq0kzs6ybqbp15nv8wdfj8gj7s7c2l470y";
  };

  urlMap = {
    i686-linux = "https://github.com/snowdreamtech/UniRTM/releases/download/v0.25.3/unirtm_Linux_i386.tar.gz";
    x86_64-linux = "https://github.com/snowdreamtech/UniRTM/releases/download/v0.25.3/unirtm_Linux_x86_64.tar.gz";
    armv7l-linux = "https://github.com/snowdreamtech/UniRTM/releases/download/v0.25.3/unirtm_Linux_armv7.tar.gz";
    aarch64-linux = "https://github.com/snowdreamtech/UniRTM/releases/download/v0.25.3/unirtm_Linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/snowdreamtech/UniRTM/releases/download/v0.25.3/unirtm_Darwin_x86_64.tar.gz";
    aarch64-darwin = "https://github.com/snowdreamtech/UniRTM/releases/download/v0.25.3/unirtm_Darwin_arm64.tar.gz";
  };
  sourceRootMap = {
    i686-linux = "unirtm_Linux_i386";
    x86_64-linux = "unirtm_Linux_x86_64";
    armv7l-linux = "unirtm_Linux_armv7";
    aarch64-linux = "unirtm_Linux_arm64";
    x86_64-darwin = "unirtm_Darwin_x86_64";
    aarch64-darwin = "unirtm_Darwin_arm64";
  };
in
stdenvNoCC.mkDerivation {
  pname = "unirtm";
  version = "0.25.3";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = sourceRootMap.${system};

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./unirtm $out/bin/unirtm
  '';

  meta = {
    description = "UniRTM (Uni Runtime and Tools Manager) is a cross-platform developer toolchain manager.";
    homepage = "https://github.com/snowdreamtech/UniRTM";
    license = lib.licenses.mit;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "armv7l-linux"
      "i686-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
