# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    i686-linux = "1sw6waw41mv3v6ljma3hhqrfm2gnvdv96swyp4pdkagf7l1hp1d2";
    x86_64-linux = "1ah7ssgl0icpd672gh1zz33j5b2q9d7cwj4qbfzvllxv3862n123";
    armv7l-linux = "1c763nbdma9iaavw67yblppcmln4gv1yq2yq1rvla6xym67l8k1k";
    aarch64-linux = "07a0r54jfaxwd2gvn000wgs2bk05wwh2w6pgp6vv8c2qqpmsx58k";
    x86_64-darwin = "16k5c1xb2411da1dxp1c9qwm6k6vdd85s5bbri60f36r5nw0660r";
    aarch64-darwin = "1xp91hdyki2xw9smyr87c0bkbhh46i9qc8gxyyykdv2j7vnhxy5p";
  };

  urlMap = {
    i686-linux = "https://github.com/snowdreamtech/UniRTM/releases/download/v0.33.2/unirtm_Linux_i386.tar.gz";
    x86_64-linux = "https://github.com/snowdreamtech/UniRTM/releases/download/v0.33.2/unirtm_Linux_x86_64.tar.gz";
    armv7l-linux = "https://github.com/snowdreamtech/UniRTM/releases/download/v0.33.2/unirtm_Linux_armv7.tar.gz";
    aarch64-linux = "https://github.com/snowdreamtech/UniRTM/releases/download/v0.33.2/unirtm_Linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/snowdreamtech/UniRTM/releases/download/v0.33.2/unirtm_Darwin_x86_64.tar.gz";
    aarch64-darwin = "https://github.com/snowdreamtech/UniRTM/releases/download/v0.33.2/unirtm_Darwin_arm64.tar.gz";
  };
  sourceRootMap = {
    i686-linux = "unirtm_Linux_i386";
    x86_64-linux = "unirtm_Linux_x86_64";
    armv7l-linux = "unirtm_Linux_armv7";
    aarch64-linux = "unirtm_Linux_arm64";
    x86_64-darwin = "unirtm_Darwin_x86_64";
    aarch64-darwin = "unirtm_Darwin_arm64";
  };
in
stdenvNoCC.mkDerivation {
  pname = "unirtm";
  version = "0.33.2";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = sourceRootMap.${system};

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    runHook preInstall
    mkdir -p $out/bin
    cp -vr ./unirtm $out/bin/unirtm
    runHook postInstall
  '';

  meta = {
    description = "UniRTM (Uni Runtime and Tools Manager) is a cross-platform developer toolchain manager.";
    homepage = "https://github.com/snowdreamtech/UniRTM";
    license = lib.licenses.mit;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "armv7l-linux"
      "i686-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
