# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    i686-linux = "1ymn7vibdr64nngci35xzcshqaq0xpqkvxgn926fg22bm5kq4gha";
    x86_64-linux = "0wgzy019gd91l8z2hrz4s8xfj5nrr19sxqk7avq97giycpcc2ma6";
    armv7l-linux = "0j5cq0j7b6kfzs0f9l5vypv0h4r4k9fn4kbnbdg1m0nj3gyc85nq";
    aarch64-linux = "1fwlw06ndawl335m0486r93hw5vl1db4qxarf19fkvqlw6agvy37";
    x86_64-darwin = "1wk94lk651pc9khfmbhgxq863l2bksvnqfmb4xd7narjbpvqan7f";
    aarch64-darwin = "0n5lnr6lpxk5zrcbvb71hpf050y0n0751j92facc7h720lp6zivp";
  };

  urlMap = {
    i686-linux = "https://github.com/snowdreamtech/unigo/releases/download/v0.0.2/unigo_Linux_i386.tar.gz";
    x86_64-linux = "https://github.com/snowdreamtech/unigo/releases/download/v0.0.2/unigo_Linux_x86_64.tar.gz";
    armv7l-linux = "https://github.com/snowdreamtech/unigo/releases/download/v0.0.2/unigo_Linux_armv7.tar.gz";
    aarch64-linux = "https://github.com/snowdreamtech/unigo/releases/download/v0.0.2/unigo_Linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/snowdreamtech/unigo/releases/download/v0.0.2/unigo_Darwin_x86_64.tar.gz";
    aarch64-darwin = "https://github.com/snowdreamtech/unigo/releases/download/v0.0.2/unigo_Darwin_arm64.tar.gz";
  };
  sourceRootMap = {
    i686-linux = "unigo_Linux_i386";
    x86_64-linux = "unigo_Linux_x86_64";
    armv7l-linux = "unigo_Linux_armv7";
    aarch64-linux = "unigo_Linux_arm64";
    x86_64-darwin = "unigo_Darwin_x86_64";
    aarch64-darwin = "unigo_Darwin_arm64";
  };
in
stdenvNoCC.mkDerivation {
  pname = "unigo";
  version = "0.0.2";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = sourceRootMap.${system};

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./unigo $out/bin/unigo
  '';

  meta = {
    description = "Snowdream Tech AI IDE Template is an enterprise-grade, foundational template designed for multi-AI IDE collaboration.";
    homepage = "https://github.com/snowdreamtech/unigo";
    license = lib.licenses.mit;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "armv7l-linux"
      "i686-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
