# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    i686-linux = "16zixwh2bsyn3i2sp7ddjr2rxf4agcyzciq60k1br4283a09vz76";
    x86_64-linux = "1dhys9s5zvyg9k60k8bjvnzxd4f9xh0irl4r5vag82f9f5ckf38b";
    armv7l-linux = "0n46mr1jzq09khc8f23aamkndr5qklm70v31c4fj1q6rxhlv5zs1";
    aarch64-linux = "1zb4y1d28d6lj3hxdfndcmssa2zl1mrdsp29vyri5f1krlgkff3w";
    x86_64-darwin = "0m55kza91d72xaqd444365ks7xp7x3yla6grapdqijxpwsaf33f9";
    aarch64-darwin = "0qbxfkxjqyv85s2arjnq75gsfmlckaqh2ahc11mqp6wl9zjh7nnh";
  };

  urlMap = {
    i686-linux = "https://github.com/snowdreamtech/unigo/releases/download/v0.0.1/unigo_Linux_i386.tar.gz";
    x86_64-linux = "https://github.com/snowdreamtech/unigo/releases/download/v0.0.1/unigo_Linux_x86_64.tar.gz";
    armv7l-linux = "https://github.com/snowdreamtech/unigo/releases/download/v0.0.1/unigo_Linux_armv7.tar.gz";
    aarch64-linux = "https://github.com/snowdreamtech/unigo/releases/download/v0.0.1/unigo_Linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/snowdreamtech/unigo/releases/download/v0.0.1/unigo_Darwin_x86_64.tar.gz";
    aarch64-darwin = "https://github.com/snowdreamtech/unigo/releases/download/v0.0.1/unigo_Darwin_arm64.tar.gz";
  };
  sourceRootMap = {
    i686-linux = "unigo_Linux_i386";
    x86_64-linux = "unigo_Linux_x86_64";
    armv7l-linux = "unigo_Linux_armv7";
    aarch64-linux = "unigo_Linux_arm64";
    x86_64-darwin = "unigo_Darwin_x86_64";
    aarch64-darwin = "unigo_Darwin_arm64";
  };
in
stdenvNoCC.mkDerivation {
  pname = "unigo";
  version = "0.0.1";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = sourceRootMap.${system};

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./unigo $out/bin/unigo
  '';

  meta = {
    description = "Snowdream Tech AI IDE Template is an enterprise-grade, foundational template designed for multi-AI IDE collaboration.";
    homepage = "https://github.com/snowdreamtech/unigo";
    license = lib.licenses.mit;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "armv7l-linux"
      "i686-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
