# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    i686-linux = "17379w3rmhiq78pxkkm2az805wjih5ygmx6fi6a0pr3hxa26sjyh";
    x86_64-linux = "1ryfdsn6qhzjnf331kgxs5qz9chk4d7yp4qdy0a5xcvv3rqvkjkr";
    armv7l-linux = "01n3zr5pycah1ka3si030p70r10rj83j914ml0frdi9989qvv31l";
    aarch64-linux = "1vhss6xqxs7rdcz79xn2bkg337y3gxdd43clynqf4671lwjb7v59";
    x86_64-darwin = "172f1y90kx9s5bjxzxwb6zbk03gjvgym74bf4killq9smrxnpah4";
    aarch64-darwin = "15j7q9y01jmvjm7h3qc8ag1g44893xhzm80qkw2bf562ljqvx3fr";
  };

  urlMap = {
    i686-linux = "https://github.com/snowdreamtech/unigo/releases/download/v0.0.5/unigo_Linux_i386.tar.gz";
    x86_64-linux = "https://github.com/snowdreamtech/unigo/releases/download/v0.0.5/unigo_Linux_x86_64.tar.gz";
    armv7l-linux = "https://github.com/snowdreamtech/unigo/releases/download/v0.0.5/unigo_Linux_armv7.tar.gz";
    aarch64-linux = "https://github.com/snowdreamtech/unigo/releases/download/v0.0.5/unigo_Linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/snowdreamtech/unigo/releases/download/v0.0.5/unigo_Darwin_x86_64.tar.gz";
    aarch64-darwin = "https://github.com/snowdreamtech/unigo/releases/download/v0.0.5/unigo_Darwin_arm64.tar.gz";
  };
  sourceRootMap = {
    i686-linux = "unigo_Linux_i386";
    x86_64-linux = "unigo_Linux_x86_64";
    armv7l-linux = "unigo_Linux_armv7";
    aarch64-linux = "unigo_Linux_arm64";
    x86_64-darwin = "unigo_Darwin_x86_64";
    aarch64-darwin = "unigo_Darwin_arm64";
  };
in
stdenvNoCC.mkDerivation {
  pname = "unigo";
  version = "0.0.5";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = sourceRootMap.${system};

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./unigo $out/bin/unigo
  '';

  meta = {
    description = "Snowdream Tech AI IDE Template is an enterprise-grade, foundational template designed for multi-AI IDE collaboration.";
    homepage = "https://github.com/snowdreamtech/unigo";
    license = lib.licenses.mit;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "armv7l-linux"
      "i686-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
